kind: Service
apiVersion: v1
metadata:
  name: memsql
  labels:
    name: memsql
    branch: master
spec:
  ports:
    - port: 3306
      protocol: TCP
      name: sql
    - port: 9000
      protocol: TCP
      name: op
