apiVersion: v1
kind: ReplicationController
metadata:
  name: authenticator
  labels:
    name: authenticator
    branch: master
spec:
  replicas: 2
  # selector identifies the set of pods that this
  # replication controller is responsible for managing
  selector:
    name: authenticator
    branch: master
  # template defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: authenticator
        branch: master
    spec:
      containers:
      - name: authenticator
        command: ["npm", "start", "--"]
        args: ["--ws-url", "ws://crossbar-private:8081"]
        image: eu.gcr.io/saio-fr/authenticator:master
        ports:
        - containerPort: 8081
