kind: Endpoints
apiVersion: v1
metadata:
  name: memsql
  labels:
    name: memsql
    branch: master
subsets:
- addresses:
  - IP: 10.240.21.210
  ports:
  - port: 3306
    protocol: TCP
    name: sql
  - port: 9000
    protocol: TCP
    name: op
